---
sidebar: sidebar 
permalink: deploy-fsx-file-system-native.html 
keywords: vm workloads, deploy fsx, deploy storage for vms 
summary: 'Après avoir vérifié que la solution FSX pour le système de fichiers ONTAP recommandée, ou dans certains cas, répond exactement à vos exigences, vous pouvez utiliser l"usine de workloads pour déployer le système dans votre environnement AWS.' 
---
= Déployez le système de fichiers FSX pour ONTAP recommandé par les workloads VMware
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Après avoir vérifié que le système de fichiers FSX pour ONTAP recommandé (ou plusieurs systèmes de fichiers dans certains cas) répond exactement à vos exigences, vous pouvez utiliser l'usine de workloads pour déployer le système dans votre environnement AWS.

Selon la règle et les autorisations que vous avez ajoutées au compte d'usine de votre workload, vous pouvez déployer complètement le système de fichiers FSX pour ONTAP en utilisant la fabrique de workloads (en mode automatisé). Si vous avez moins d'autorisations (mode lecture) ou pas d'autorisations (mode base), vous devez utiliser les informations CloudFormation de la Codebox et déployer vous-même le système de fichiers FSX pour ONTAP dans AWS.

.Configuration requise pour les déploiements sur Amazon EC2
* Le volume root du système de fichiers FSX pour ONTAP doit être créé en tant que volume EBS.


.Étapes
. Au bas de la page *Plan d'examen*, sélectionnez *déployer* et la page Créer un système de fichiers FSX pour ONTAP s'affiche.
+
La plupart des champs qui définissent votre système de fichiers FSX pour ONTAP sont remplis en fonction des informations que vous avez fournies, mais vous devez remplir quelques champs dans cette page.

+
Vous pouvez utiliser l'option création rapide ou création avancée. La création avancée offre quelques paramètres de stockage supplémentaires que vous pouvez personnaliser. https://docs.netapp.com/us-en/workload-fsx-ontap/create-file-system.html["Découvrez les avantages de ces deux options"]

. *Informations d'identification AWS* : sélectionnez ou ajoutez des informations d'identification qui donneront à Workload Factory les autorisations nécessaires pour créer directement votre système de fichiers FSX pour ONTAP. Vous pouvez également sélectionner le code CloudFormation dans Codebox et déployer vous-même le système de fichiers FSX pour ONTAP dans AWS.
. *Nom du système de fichiers* : saisissez le nom que vous souhaitez utiliser pour ce système de fichiers FSX for ONTAP.
. *Balises* : vous pouvez éventuellement ajouter des balises pour classer ce système de fichiers FSX pour ONTAP.
. Dans la section « réseau et sécurité », entrez les informations suivantes :
+
.. *Région et VPC* : sélectionnez la région et le VPC où le système de fichiers FSX pour ONTAP sera déployé.
+
Si vous déployez sur VMware Cloud on AWS, assurez-vous de le déployer dans un VPC différent du VPC dans lequel le cloud VMware sur AWS est déployé.

.. *Groupe de sécurité* : lorsque vous utilisez l'option *création avancée*, vous pouvez sélectionner le groupe de sécurité par défaut pour le VPC FSX pour ONTAP afin que tout le trafic puisse accéder au système de fichiers FSX pour ONTAP.
+
Vous pouvez ajouter une règle entrante qui limite l'accès des autres services AWS au système de fichiers FSX pour ONTAP. Cela bloquera le nombre de services ouverts. Nombre minimal de ports et de protocoles :

+
[cols="15,10,55"]
|===
| Protocoles | Ports | Objectif 


| TCP, UDP | 111 | Portmapper (utilisé pour négocier les ports utilisés dans les requêtes NFS) 


| TCP, UDP | 635 | Montage NFS (reçoit les demandes de montage NFS) 


| TCP, UDP | 2049 | Trafic du réseau NFS 


| TCP, UDP | 4045 | Network Lock Manager (NLM, lockd) : gère les demandes de verrouillage. 


| TCP, UDP | 4046 | Network Status Monitor (NSM, statd) : informe les clients NFS des redémarrages du serveur pour la gestion des verrous. 
|===
.. *Zone de disponibilité* : sélectionnez la zone de disponibilité et le sous-réseau.
+
Vous devez sélectionner la même zone de disponibilité que celle où votre SDDC VMware est déployé si vous souhaitez éviter les frais de trafic entre AZ.

.. *Encryption* : lorsque vous utilisez l'option *Advanced create*, vous pouvez sélectionner le nom de la clé de cryptage AWS dans la liste déroulante.
.. *Contrôle d'accès au datastore* : lorsque vous utilisez l'option *Advanced create*, vous pouvez indiquer si tous les hôtes peuvent accéder aux datastores ou si seuls certains nœuds de cluster vSphere d'un sous-réseau spécifique peuvent accéder aux datastores.


. Dans la section « Détails du système de fichiers », entrez les informations suivantes :
+
.. *Informations d'identification ONTAP* : saisissez et confirmez le mot de passe ONTAP.
.. *Informations d'identification de la machine virtuelle de stockage* (création avancée uniquement) : saisissez et confirmez le mot de passe de la machine virtuelle de stockage. Le mot de passe peut être spécifique à ce système de fichiers ou vous pouvez utiliser le même mot de passe que celui saisi pour les informations d'identification ONTAP.


. Dans la section *Résumé*, vous pouvez afficher la configuration du système de fichiers et du datastore FSX pour ONTAP conçue par VMware migration Advisor en fonction de vos informations.
. Sélectionnez *Créer* pour déployer le système de fichiers FSX pour ONTAP. Ce processus peut prendre jusqu'à 2 heures.
+
Dans la fenêtre Codebox, vous pouvez sélectionner *rediriger vers CloudFormation* pour créer le système de fichiers à l'aide d'une pile CloudFormation.

+
Dans les deux cas, vous pouvez surveiller la progression de la création dans CloudFormation.



.Résultat
Le système de fichiers FSX for ONTAP est déployé.
