---
sidebar: sidebar 
permalink: launch-migration-advisor-evs-manual.html 
keywords: overview, concepts, features, use case, workloads, how Workload Factory works, migration, manual, specification, deploy, deployment, plan 
summary: Connectez-vous à NetApp Workload Factory pour accéder au centre de planification VMware.  Vous pouvez créer manuellement un plan de déploiement pour EVS. 
---
= Créer manuellement un plan de déploiement pour Amazon EVS
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Connectez-vous à NetApp Workload Factory pour accéder au centre de planification VMware.  À partir de là, vous pouvez créer manuellement un plan de déploiement ou un plan de migration pour Amazon EVS personnalisé en fonction de vos besoins.

Notez que vous devez disposer d'un nom d'utilisateur et d'un mot de passe pour accéder à Workload Factory.  Si vous n'avez pas accès, créez un compte maintenant.  Voir les instructions https://docs.netapp.com/us-en/workload-setup-admin/quick-start.html["ici"] .



== Créer un plan de déploiement en spécifiant manuellement les exigences environnementales

Vous pouvez spécifier manuellement vos exigences en matière de machines virtuelles dans Amazon Elastic VMware Service et utiliser des systèmes de fichiers Amazon FSx for NetApp ONTAP personnalisés comme banques de données externes.

.De formation
* Vous devez disposer d’un abonnement Amazon Elastic VMware Service.


.Étapes
. Connectez-vous à Workload Factory en utilisant l'un des https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["expériences de la console"^] .
. Si vous avez accédé à Workload Factory à partir de la console Workload Factory, dans la mosaïque Charges de travail VMware, sélectionnez *Centre de planification VMware*, puis sélectionnez *Centre de planification VMware*.  Le centre de planification VMware s'affiche.
. Sélectionnez *Créer manuellement un plan EVS*.
. Saisissez les exigences pour votre environnement VM.
+
[NOTE]
====
Gardez à l’esprit les exigences et recommandations de performances de migration de machine virtuelle suivantes :

** Une capacité de stockage minimale de 10 Tio est recommandée pour l’inventaire des machines virtuelles pour des raisons de performances.
** Un débit minimum est requis pour les magasins de données Amazon Elastic VMware Service, en fonction du nombre d'IOPS requis que vous spécifiez pour ce déploiement.
** Selon la configuration du système de fichiers FSx for ONTAP, un nombre minimum de banques de données externes est requis pour que l'environnement Amazon Elastic VMware Service atteigne des performances optimales.


====
. Lorsque vous êtes prêt, sélectionnez *Consulter le plan* pour examiner le plan de migration.
. Revoir le plan. Développez chaque section pour afficher les détails du plan.
+
Par défaut, Workload Factory enregistre le plan de migration dans le centre de planification.  Vous pouvez désélectionner cette option en haut de la page.

. En option, lorsque vous êtes satisfait du plan de migration, vous pouvez télécharger les détails du plan sous forme de document PDF en sélectionnant *Exporter le plan (PDF)*.
. Lorsque vous êtes prêt à provisionner le plan de déploiement, sélectionnez *Provision*.


link:deploy-fsx-file-system-evs.html["Déployez le système de fichiers FSX pour ONTAP recommandé par les workloads VMware"].
