---
sidebar: sidebar 
permalink: learn-about-vmware-workloads.html 
keywords: overview, concepts, features, use case, workloads, how Workload Factory works 
summary: 'NetApp Workload Factory pour VMware fournit des outils pour déplacer vos données des systèmes sur site vers Amazon EVS, VMware Cloud on AWS (VMC) ou Amazon EC2.' 
---
= En savoir plus sur NetApp Workload Factory pour VMware
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp Workload Factory for VMware fournit des outils pour déplacer vos données des systèmes sur site vers Amazon Elastic VMware Service (EVS), VMware Cloud on AWS (VMC) ou Amazon EC2.



== Qu'est-ce que NetApp Workload Factory pour VMware ?

NetApp Workload Factory for VMware fournit un centre de planification et des conseillers de migration qui vous permettent d'analyser vos configurations de machines virtuelles actuelles dans les environnements vSphere sur site.  Les conseillers en migration génèrent ensuite un plan pour déployer les configurations de machines virtuelles recommandées sur les clusters Amazon EVS, Amazon EC2 ou VMware Cloud sur AWS vSphere et utilisent des systèmes de fichiers Amazon FSx for NetApp ONTAP personnalisés comme banques de données externes.  Le centre de planification, agissant comme tableau de bord Workload Factory pour VMware, vous permet de gérer les ensembles de données d'inventaire de machines virtuelles enregistrés, ainsi que les plans de migration enregistrés, et de provisionner tous les plans de migration que vous avez enregistrés.

Amazon FSx for NetApp ONTAP est une banque de données NFS externe construite sur le système de fichiers ONTAP de NetApp qui peut être attachée à des instances Amazon EVS ou Amazon EC2 ou à des clusters VMware Cloud sur AWS vSphere.  Il n’est pas nécessaire d’ajouter davantage d’hôtes pour augmenter le stockage disponible ; utilisez plutôt FSx pour les volumes ONTAP comme banques de données externes pour compléter les banques de données vSAN.  Cela vous fournit une infrastructure de stockage virtualisée flexible et hautes performances qui s'adapte indépendamment des ressources de calcul.

Pour plus d'informations sur Workload Factory, reportez-vous au https://docs.netapp.com/us-en/workload-setup-admin/workload-factory-overview.html["Présentation de Workload Factory"^] .



== Comment fonctionnent les conseillers en migration VMware

Les conseillers en migration peuvent vous aider à déplacer des machines virtuelles (VM) sur site et leurs données, exécutées sur n'importe quel magasin de données pris en charge par VMware, vers des magasins de données Amazon EVS, Amazon EC2 ou VMware Cloud, qui incluent des magasins de données NFS supplémentaires sur un système de fichiers FSx pour ONTAP .

Notez que vous pouvez connecter jusqu'à quatre (4) volumes FSX pour ONTAP à un seul cluster vSphere sur VMware Cloud on AWS.



== Ce que vous pouvez faire avec les conseillers en migration

Les conseillers en migration offrent les fonctionnalités suivantes :

* Analysez les configurations de VM sur site
* Déterminer les machines virtuelles à migrer vers Amazon EC2, Amazon EVS ou VMware Cloud on AWS
* Identifiez l'espace requis sur les volumes FSX pour ONTAP à utiliser en tant que datastores externes de VM
* Examinez le rapport résultant pour comprendre les étapes de déploiement
* Effectuer le déploiement réel


Le conseiller de migration prend en charge la planification de la configuration d'une seule instance Amazon EVS ou Amazon EC2 ou d'un cluster VMware Cloud on AWS connecté à un seul système de fichiers FSx for ONTAP .



== Avantages de faire appel à des conseillers en migration

Le transfert d'une partie de votre infrastructure actuelle vers Amazon EC2 ou VMware Cloud on AWS à l'aide d'Amazon FSX for ONTAP en tant que datastores NFS externes offre les avantages suivants :

* Optimisation des coûts grâce au découplage de l'hôte et du stockage et à une efficacité avancée des données
* Possibilité de développer la capacité de stockage en fonction des besoins sans avoir à acheter d'instances hôtes supplémentaires
* Les fonctionnalités de gestion des données NetApp ONTAP dans le cloud, comme les copies Snapshot compactes, le clonage, la compression, la déduplication, la compaction et la réplication
* Réduction de la gestion des mises à jour matérielles
* Possibilité de modifier le débit des données, les IOPS et la taille du système de fichiers en plus d'augmenter ou de réduire la taille des volumes
* Haute disponibilité prenant en charge les déploiements dans plusieurs zones de disponibilité (AZ)
* Réduction des coûts et de la latence grâce à des configurations AZ uniques qui utilisent le peering VPC sans nécessiter de passerelle de transit




== Outils pour utiliser NetApp Workload Factory

Vous pouvez utiliser NetApp Workload Factory avec les outils suivants :

* *Console Workload Factory* : La console Workload Factory fournit une vue visuelle et holistique de vos applications et projets.
* * Console NetApp * : la console NetApp fournit une expérience d'interface hybride afin que vous puissiez utiliser Workload Factory avec d'autres services de données NetApp .
* *Demandez-moi* : utilisez l'assistant IA Ask me pour poser des questions et en savoir plus sur Workload Factory sans quitter la console Workload Factory. Accédez à Demandez-moi depuis le menu d'aide de Workload Factory.
* *CloudShell CLI* : Workload Factory inclut une CLI CloudShell pour gérer et exploiter les environnements AWS et NetApp sur plusieurs comptes à partir d'une seule CLI basée sur un navigateur. Accédez à CloudShell depuis la barre supérieure de la console Workload Factory.
* *API REST* : utilisez les API REST de Workload Factory pour déployer et gérer vos systèmes de fichiers FSx for ONTAP et d'autres ressources AWS.
* *CloudFormation* : utilisez le code AWS CloudFormation pour effectuer les actions que vous avez définies dans la console Workload Factory afin de modéliser, provisionner et gérer les ressources AWS et tierces de la pile CloudFormation dans votre compte AWS.
* *Fournisseur Terraform NetApp Workload Factory* : utilisez Terraform pour créer et gérer les workflows d'infrastructure générés dans la console Workload Factory.




== Le coût

L’utilisation de Workload Factory pour VMware est gratuite.

Vous devrez payer pour les ressources AWS que vous déployez en fonction des recommandations des conseillers en migration.



== Licences

Aucune licence spéciale de NetApp n'est requise pour utiliser Workload Factory pour VMware.



== Régions

Workload Factory est pris en charge dans toutes les régions commerciales où FSx for ONTAP est pris en charge. https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/["Afficher les régions Amazon prises en charge."^]

Les régions AWS suivantes ne sont pas prises en charge :

* régions de Chine
* Régions GovCloud (États-Unis)
* Nuage secret
* Nuage top secret

