---
settings:
  name: VMware workloads
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  release_notes_autogen:
    release_notes_repo: workload-relnotes
  langs: fr-fr,us-en,de-de,es-es,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentation sur les workloads VMware
    url: "/index.html"
  - title: Notes de mise à jour
    entries:
    - title: Quoi de neuf
      url: "/whats-new.html"
  - title: Commencez
    entries:
    - title: En savoir plus sur NetApp Workload Factory pour VMware
      url: "/learn-about-vmware-workloads.html"
    - title: Démarrage rapide pour la migration vers Amazon EVS
      url: "/quick-start-evs.html"
    - title: Démarrage rapide de la migration vers Amazon EC2
      url: "/quick-start-native.html"
    - title: Démarrage rapide de la migration vers VMware Cloud sur AWS
      url: "/quick-start.html"
    - title: Explorez le centre de planification VMware
      url: "/explore-planning-center.html"
  - title: Utiliser le centre de planification VMware
    entries:
    - title: Télécharger les données d'inventaire de la machine virtuelle
      url: "/upload-vm-inventory.html"
    - title: Migrer vers Amazon Elastic VMware Service
      entries:
      - title: Explorez les économies
        url: "/calculate-evs-savings.html"
      - title: Créer manuellement un plan de déploiement
        url: "/launch-migration-advisor-evs-manual.html"
      - title: Créez un plan de déploiement à l'aide du conseiller de migration
        url: "/launch-migration-advisor-evs.html"
      - title: Déployez le système de fichiers FSX pour ONTAP recommandé
        url: "/deploy-fsx-file-system-evs.html"
    - title: Migrez vers Amazon EC2
      entries:
      - title: Créez un plan de déploiement à l'aide du conseiller de migration
        url: "/launch-onboarding-advisor-native.html"
      - title: Déployez le système de fichiers FSX pour ONTAP recommandé
        url: "/deploy-fsx-file-system-native.html"
    - title: Migrez vers VMware Cloud on AWS
      entries:
      - title: Créez un plan de déploiement à l'aide du conseiller de migration
        url: "/launch-onboarding-advisor.html"
      - title: Déployez le système de fichiers FSX pour ONTAP recommandé
        url: "/deploy-fsx-file-system.html"
      - title: Connectez FSX pour ONTAP à VMware Cloud sur AWS
        url: "/connect-sddc-to-fsx.html"
      - title: Migrez vos données vers la nouvelle infrastructure
        url: "/migrate-data.html"
  - title: Administrer et surveiller
    entries:
    - title: Analyse de configuration pour les configurations EVS
      url: "/configuration-analysis.html"
    - title: Mettre en œuvre des configurations EVS bien architecturées
      url: "/view-evs-well-architected.html"
  - title: Connaissances et support
    entries:
    - title: S'inscrire pour obtenir de l'aide
      url: "/support-registration.html"
    - title: Obtenez de l'aide
      url: "/get-help.html"
  - title: Mentions légales
    url: "/legal-notices.html"
product-family:
  name: NetApp Workload Factory
  repo: workload-family
