---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes' 
summary: Découvrez les nouveautés du composant VMware Migration Advisor de Workload Factory. 
---
= Nouveautés de NetApp Workload Factory pour VMware
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Découvrez les nouveautés du composant VMware Migration Advisor de Workload Factory.



== 2 novembre 2025



=== Présentation des préférences d'Amazon Elastic VMware Service dans l'assistant de déploiement du système de fichiers FSx pour ONTAP

Lorsque vous déployez un système de fichiers FSx for ONTAP destiné à être utilisé comme banque de données NFS externe pour Amazon Elastic VMware Service, vous pouvez désormais sélectionner l'environnement EVS auquel les banques de données seront connectées.  Cela permet de remplir automatiquement plusieurs champs de l'assistant de déploiement afin de simplifier le processus de déploiement.

https://docs.netapp.com/us-en/workload-vmware/deploy-fsx-file-system-evs.html["Déployez le système de fichiers FSX pour ONTAP recommandé"]



=== Modifications des autorisations pour les charges de travail VMware

VMware Workloads offre une meilleure visibilité sur les autorisations requises pour des actions spécifiques et une granularité permettant de sélectionner uniquement les autorisations nécessaires.  Lorsque vous ajouterez des informations d'identification, vous aurez le choix entre deux options d'autorisation au lieu du modèle d'autorisation précédent qui était _lecture seule_ et _lecture/écriture_. Le nouveau modèle d'autorisations décompose les politiques d'autorisation comme suit :

* _Visualisation, planification et analyse_ : Consultez l’inventaire des environnements de virtualisation EVS, obtenez une analyse détaillée de vos systèmes et explorez les économies possibles.
* _Déploiement et connectivité des datastores_ : Déployez les configurations de machines virtuelles recommandées sur les clusters Amazon EVS, Amazon EC2 ou VMware Cloud on AWS vSphere et utilisez des systèmes de fichiers Amazon FSx for NetApp ONTAP comme datastores externes.


Lors de l'ajout d'informations d'identification, vous pouvez sélectionner une ou plusieurs de ces stratégies d'autorisation en fonction du niveau d'accès que vous souhaitez accorder aux charges de travail VMware.

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html["Référence des autorisations de Workload Factory"^]



=== Améliorations d'Amazon EC2 migration Advisor

Cette version de NetApp Workload Factory pour VMware présente plusieurs améliorations de l'expérience du conseiller de migration :

* *Enregistrer ou télécharger un plan de migration* : Vous pouvez désormais enregistrer ou télécharger un plan de migration au format PDF ou CSV.  Lorsque vous enregistrez un plan de migration, celui-ci est enregistré sur votre compte Workload Factory.




== 5 octobre 2025



=== BlueXP workload factory désormais NetApp Workload Factory

BlueXP a été renommé et repensé pour mieux refléter le rôle qu'il joue dans la gestion de votre infrastructure de données. Par conséquent, BlueXP workload factory a été renommée NetApp Workload Factory.



=== Présentation du centre de planification des charges de travail VMware

Le centre de planification des charges de travail VMware vous permet d'afficher et de gérer votre inventaire de machines virtuelles et vos plans de migration à partir d'un seul endroit.  Vous pouvez télécharger et enregistrer plusieurs inventaires de machines virtuelles à partir de différents environnements et commencer à planifier une migration vers le service AWS EC2 ou Amazon Elastic VMware pour l'un d'entre eux.  Vous pouvez également créer et enregistrer des plans de migration AWS EC2 ou EVS.

https://docs.netapp.com/us-en/workload-vmware/explore-planning-center.html["Explorez le centre de planification des charges de travail VMware"]



=== Présentation de la prise en charge du conseiller de migration pour Amazon Elastic VMware Service

BlueXP Workload Factory pour VMware vous permet désormais d'utiliser le conseiller de migration Amazon Elastic VMware Service pour migrer rapidement vos charges de travail VMware sur site vers Amazon Elastic VMware Service.  Une fois que vous avez créé un plan de migration à l’aide du conseiller de migration, il est automatiquement enregistré dans la liste des plans de migration du centre de planification.

https://docs.netapp.com/us-en/workload-vmware/launch-migration-advisor-evs.html["Créer un plan de déploiement pour Amazon EVS à l'aide du conseiller de migration"]



== 3 août 2025



=== Prise en charge améliorée du conseiller de migration pour Amazon Elastic VMware Service

NetApp Workload Factory prend désormais en charge le déploiement et le montage automatiques de votre système de fichiers Amazon FSx for NetApp ONTAP .  Cela vous permet de commencer à déployer vos machines virtuelles sur les systèmes de fichiers FSx for ONTAP une fois la migration vers l'environnement Amazon EVS terminée.

https://docs.netapp.com/us-en/workload-vmware/launch-migration-advisor-evs-manual.html["Créer un plan de déploiement pour Amazon EVS à l'aide du conseiller de migration"]



=== Calculez les économies réalisées lors de la migration vers Amazon Elastic VMware Service

Vous pouvez désormais explorer les économies potentielles liées à la migration de vos charges de travail VMware vers Amazon Elastic VMware Service (EVS).  Le calculateur d'économies vous permet de comparer les coûts d'utilisation d'Amazon EVS avec et sans Amazon FSx for NetApp ONTAP comme stockage sous-jacent.  Le calculateur affiche les économies potentielles en temps réel à mesure que vous ajustez les caractéristiques de votre environnement.

https://docs.netapp.com/us-en/workload-vmware/calculate-evs-savings.html["Découvrez les économies réalisées sur Amazon Elastic VMware Service avec BlueXP Workload Factory"]



== 29 juin 2025



=== Présentation de la prise en charge du conseiller de migration pour Amazon Elastic VMware Service

BlueXP Workload Factory pour VMware prend désormais en charge Amazon Elastic VMware Service. Vous pouvez migrer manuellement vos charges de travail VMware sur site vers Amazon Elastic VMware Service, optimisant ainsi les coûts et permettant un meilleur contrôle sur votre environnement VMware sans avoir à refactoriser ou à re-plateformer vos applications.

https://docs.netapp.com/us-en/workload-vmware/launch-migration-advisor-evs-manual.html["Créer un plan de déploiement pour Amazon EVS à l'aide du conseiller de migration"]



== 4 mai 2025



=== Améliorations d'Amazon EC2 migration Advisor

Cette version de BlueXP Workload Factory pour VMware présente l'amélioration suivante de l'expérience du conseiller de migration Amazon EC2 :

*Informations sur l'infrastructure de données NetApp en tant que source de données* : la fabrique de workloads se connecte désormais directement aux informations sur l'infrastructure de données NetApp pour collecter des informations sur le déploiement VMware lorsque vous utilisez le collecteur de données EC2 migration Advisor.

https://docs.netapp.com/us-en/workload-vmware/launch-onboarding-advisor-native.html["Créez un plan de déploiement pour Amazon EC2 à l'aide du conseiller de migration"]



=== Mise à jour de la terminologie des autorisations

L'interface utilisateur et la documentation de Workload Factory utilisent désormais « lecture seule » pour faire référence aux autorisations de lecture et « lecture/écriture » pour faire référence aux autorisations d'automatisation.



== 30 mars 2025



=== Améliorations d'Amazon EC2 migration Advisor

Cette version de BlueXP Workload Factory pour VMware présente plusieurs améliorations de l'expérience du conseiller de migration Amazon EC2 :

* *Conseils améliorés d'attribution de volume* : les informations d'affectation de volume des étapes « classifier » et « Package » du conseiller de migration EC2 offrent une meilleure lisibilité et une plus grande facilité d'utilisation. Des informations plus utiles s'affichent sur chaque volume pour vous permettre de mieux identifier les volumes et de déterminer comment les attribuer.
* *Améliorations de l'efficacité du script du collecteur de données* : le script du collecteur de données EC2 migration Advisor optimise l'utilisation du processeur lors de la collecte de données pour les déploiements de machines virtuelles plus petits.


https://docs.netapp.com/us-en/workload-vmware/launch-onboarding-advisor-native.html["Créez un plan de déploiement pour Amazon EC2 à l'aide du conseiller de migration"]



== 2 mars 2025



=== Améliorations d'Amazon EC2 migration Advisor

Cette version de BlueXP Workload Factory pour VMware présente plusieurs améliorations de l'expérience du conseiller de migration Amazon EC2 :

* *Estimation du type d'instance* : migration Advisor peut désormais examiner les exigences de votre environnement et fournir un type d'instance Amazon EC2 estimé pour chaque machine virtuelle. Vous pouvez choisir d'inclure le type d'instance estimé pour chaque machine virtuelle pendant l'étape Scope de l'assistant de migration.
* *Possibilité de recommander des volumes Amazon EBS* : le conseiller en migration peut désormais recommander la migration des volumes de données vers Amazon Elastic Block Store (EBS) plutôt que vers Amazon FSX pour NetApp ONTAP en raison des besoins spécifiques en termes de capacité ou de performances d'une région donnée.
* *Attribution automatique améliorée du système de fichiers* : l'affectation du système de fichiers Amazon FSX pour NetApp ONTAP a été améliorée afin de mieux optimiser les coûts et de minimiser le débit.


https://docs.netapp.com/us-en/workload-vmware/launch-onboarding-advisor-native.html["Créez un plan de déploiement pour Amazon EC2 à l'aide du conseiller de migration"]



== 5 janvier 2025



=== Améliorations d'Amazon EC2 migration Advisor

Cette version de BlueXP Workload Factory pour VMware présente plusieurs améliorations de l'expérience du conseiller de migration :

* *Enregistrer ou télécharger un plan de migration* : Vous pouvez désormais enregistrer ou télécharger un plan de migration et charger le plan de migration pour remplir le conseiller de migration.  Lorsque vous enregistrez un plan de migration, le plan est enregistré avec votre compte Workload Factory.
* *Sélection de machine virtuelle améliorée* : BlueXP Workload Factory pour VMware prend désormais en charge le filtrage et la recherche de la liste des machines virtuelles que vous souhaitez inclure dans votre déploiement de migration.


https://docs.netapp.com/us-en/workload-vmware/launch-onboarding-advisor-native.html["Créez un plan de déploiement pour Amazon EC2 à l'aide du conseiller de migration"]



== 1er décembre 2024



=== Améliorations d'Amazon EC2 migration Advisor

Cette version de NetApp Workload Factory pour VMware présente plusieurs améliorations de l'expérience du conseiller de migration :

* *Collecte de données* : BlueXP Workload Factory pour VMware prend en charge la possibilité de collecter des données pour une période spécifique lorsque vous utilisez le conseiller de migration.
* *Sélection de VM* : BlueXP Workload Factory pour VMware prend désormais en charge la sélection des VM que vous souhaitez inclure dans votre déploiement de migration.
* *Quick vs Advanced Experience* : lorsque vous utilisez le conseiller de migration, vous pouvez désormais choisir une expérience de migration rapide, en utilisant RVTools, ou l'expérience avancée, qui utilise le collecteur de données de migration Advisor.


https://docs.netapp.com/us-en/workload-vmware/launch-onboarding-advisor-native.html["Créez un plan de déploiement pour Amazon EC2 à l'aide du conseiller de migration"]



== 3 novembre 2024



=== Aide de VMware migration Advisor sur le taux de réduction des données

Cette version de Workload Factory pour VMware est dotée d'un assistant de réduction des taux de données. L'assistant de réduction des taux de données vous aide à décider quel ratio convient le mieux à votre inventaire et à votre environnement de stockage VMware lors de la préparation de l'intégration au cloud AWS.

https://docs.netapp.com/us-en/workload-vmware/launch-onboarding-advisor-native.html["Créez un plan de déploiement pour Amazon EC2 à l'aide du conseiller de migration"]



== 19 septembre 2024



=== Améliorations de VMware migration Advisor

Cette version de Workload Factory pour VMware présente des améliorations de fonctionnalités et de stabilité, ainsi que la possibilité d'importer et d'exporter des plans de migration lors de l'utilisation du conseiller de migration VMware.

https://docs.netapp.com/us-en/workload-vmware/launch-onboarding-advisor-native.html["Créez un plan de déploiement pour Amazon EC2 à l'aide du conseiller de migration"]



== 1er septembre 2024



=== Migrez vers Amazon EC2

L'usine de workloads pour VMware prend désormais en charge la migration vers Amazon EC2 à l'aide de VMware migration Advisor.



== 7 juillet 2024



=== Version initiale de Workload Factory pour VMware

La version initiale permet d'utiliser VMware migration Advisor pour analyser les configurations actuelles de vos serveurs virtuels dans les environnements vSphere sur site, et de générer un plan de déploiement des infrastructures de serveurs virtuels recommandées dans VMware Cloud on AWS et d'utiliser des systèmes de fichiers Amazon FSX for NetApp ONTAP personnalisés en tant que datastores externes.
