= Améliorations d'Amazon EC2 migration Advisor
:allow-uri-read: 




=== Améliorations d'Amazon EC2 migration Advisor

Cette version de BlueXP Workload Factory pour VMware présente l'amélioration suivante de l'expérience du conseiller de migration Amazon EC2 :

*Informations sur l'infrastructure de données NetApp en tant que source de données* : la fabrique de workloads se connecte désormais directement aux informations sur l'infrastructure de données NetApp pour collecter des informations sur le déploiement VMware lorsque vous utilisez le collecteur de données EC2 migration Advisor.

https://docs.netapp.com/us-en/workload-vmware/launch-onboarding-advisor-native.html["Créez un plan de déploiement pour Amazon EC2 à l'aide du conseiller de migration"]



=== Mise à jour de la terminologie des autorisations

L'interface utilisateur et la documentation de Workload Factory utilisent désormais « lecture seule » pour faire référence aux autorisations de lecture et « lecture/écriture » pour faire référence aux autorisations d'automatisation.
