= Introduction de la prise en charge de l'assistant de migration pour Google Cloud VMware Engine
:allow-uri-read: 




=== Introduction de la prise en charge de l'assistant de migration pour Google Cloud VMware Engine

NetApp Workload Factory prend désormais en charge Google Cloud VMware Engine. Vous pouvez migrer vos charges de travail VMware sur site vers Google Cloud VMware Engine en utilisant Google Cloud NetApp Volumes comme datastores NFS externes, optimisant les coûts et permettant un meilleur contrôle de votre environnement VMware sans avoir à refactoriser ni à replatformer vos applications.

L'assistant de migration Google Cloud VMware Engine fournit :

* Dimensionnement et conception automatisés des clusters Google Cloud VMware Engine avec prise en charge des types de nœuds VE1 et VE2
* Optimisation de la disposition des machines virtuelles entre les datastores internes vSAN et les datastores NFS externes Google Cloud NetApp Volumes.
* Comparaison détaillée des coûts et analyse du coût total de possession (TCO) entre les configurations utilisant uniquement vSAN et celles optimisées par Google Cloud NetApp Volumes.
* Prise en charge des niveaux de service Standard, Premium et Extreme de Google Cloud NetApp Volumes.
* Déploiement d'infrastructure en tant que code avec Terraform pour un provisionnement automatisé.

